# Publish this application to bluemix using ansible
---
- name: Publish the troll-gate to Bluemix using Ansible
  hosts: 127.0.0.1
  connection: local
  vars:
    BLUEMIX_USER: "{{ lookup('env','BLUEMIX_USER') }}"
    BLUEMIX_PASSWORD: "{{ lookup('env','BLUEMIX_PASSWORD') }}"
    org: "rak_org"
    space: "dev"
    app_name: "troll-gate"
    manifest_path: ".."
  tasks:
    - name: Auth to IBM Bluemix
      bluemix_login: >
        username="{{BLUEMIX_USER}}"
        password="{{BLUEMIX_PASSWORD}}"
        org="{{org}}"
        space="{{space}}"
    - name: CF Push App
      bluemix_push: >
        app_name="{{app_name}}"
        manifest_path="{{manifest_path}}"
